from distutils.core import setup

setup(name='ifupdown2',
      version='1.1',
      description = "ifupdown 2",
      author='Roopa Prabhu',
      author_email='roopa@cumulusnetworks.com',
      url='cumulusnetworks.com',
      packages=['ifupdown', 'ifupdownaddons'],
      data_files=[ ('/etc/network/ifupdown2/',
                      ['config/ifupdown2.conf']),
                  ('/usr/share/bash-completion/completions/', ['completion/ifup']),
                  ('/usr/share/ifupdown2/addons/', ['addons/bridge.py',
                      'addons/bond.py', 'addons/vlan.py',
                      'addons/mstpctl.py', 'addons/address.py',
                      'addons/dhcp.py', 'addons/usercmds.py',
                      'addons/ethtool.py',
                      'addons/addressvirtual.py', 'addons/vxlan.py',
                      'addons/link.py', 'addons/tunnel.py', 'addons/vrf.py',
                      'addons/bridgevlan.py', 'addons/batman_adv.py']),
                   ('/usr/share/ifupdown2/nlmanager/',
                    ['nlmanager/nllistener.py',
                     'nlmanager/nlmanager.py',
                     'nlmanager/nlpacket.py',
                     'nlmanager/__init__.py',
                     'nlmanager/README']),
                   ('/etc/network/ifupdown2/', ['config/addons.conf']),
                  ('/etc/network/ifupdown2/', ['config/addons.conf']),
                  ('/var/lib/ifupdown2/policy.d/', []),
                  ('/etc/network/ifupdown2/policy.d/', [])
                  ]
      )
