#!/bin/bash

set -e

udevlink=$(readlink /etc/udev/rules.d/80-networking.rules 2>/dev/null)
[ -n "$udevlink" -a "$udevlink" == "/dev/null" ] && rm -f /etc/udev/rules.d/80-networking.rules
udevlink=$(readlink /etc/udev/rules.d/60-bridge-network-interface.rules 2>/dev/null)
[ -n "$udevlink" -a "$udevlink" == "/dev/null" ] && rm -f /etc/udev/rules.d/60-bridge-network-interface.rules

if [ "$1" = "purge" ] ; then
    update-rc.d networking remove >/dev/null
fi
