#!/usr/bin/python
#
# Copyright 2016 Cumulus Networks, Inc. All rights reserved.
# Author: Julien Fortin, julien@cumulusnetworks.com
#
#

import sys
import json
import socket


class Ifupdown2Client:
    def __init__(self, argv):
        self.stdin = None
        self.argv = argv
        self.socket = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)

        try:
            self.socket.connect('/var/run/ifupdown2d/uds')
        except socket.error:
            self.socket.close()
            self.socket = None
            sys.stderr.write("""
    ERROR: %s could not connect to ifupdown2d

    Try starting ifupdown2d with:
    sudo systemctl start ifupdown2d

    To configure ifupdown2d to start when the box boots:
    sudo systemctl enable ifupdown2d
    """ % argv[0])

    def __del__(self):
        if self.socket:
            self.socket.close()

    def run(self):
        code = 1
        if self.socket:

            for arg in ['-i', '--interfaces']:
                try:
                    if self.argv[self.argv.index(arg) + 1] == '-':
                        self.stdin = sys.stdin.read()
                        continue
                except ValueError, IndexError:
                    pass

            self.socket.send(json.dumps({
                'argv': self.argv,
                'stdin': self.stdin
            }))

            total_data = []

            while True:
                data = self.socket.recv(4096)
                if data:
                    total_data.append(data)
                else:
                    break
            self.socket.close()
            result = json.loads(''.join(total_data)) if total_data else None
            if result:
                try:
                    code = result["code"]
                    stdout = '\n'.join(result["stdout"].split('\\n'))
                    stderr = '\n'.join(result["stderr"].split('\\n'))

                    sys.stderr.write(stderr)
                    sys.stdout.write(stdout)
                except Exception as e:
                    sys.stderr.write(str(e))
            return code
        else:
            return code


if __name__ == '__main__':
    sys.exit(Ifupdown2Client(sys.argv).run())
